name: Mirror to personal repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror
        run: |
          git remote add mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/mariosalembe23/angopen-mirror.git
          git push mirror --mirror